0:
  epoch_transitions_only: true
  max_transition_epoch: 10
  params:
  - bns2.bias
  - bns2.weight
  - bns1.bias
  - bns1.weight
  - convs3.bias
  - convs3.weight
  - convs2.bias
  - convs2.weight
  - convs1.bias
  - convs1.weight
  - propagation_0.mlp_bns.1.bias
  - propagation_0.mlp_bns.1.weight
  - propagation_0.mlp_bns.0.bias
  - propagation_0.mlp_bns.0.weight
  - propagation_0.mlp_convs.1.bias
  - propagation_0.mlp_convs.1.weight
  - propagation_0.mlp_convs.0.bias
  - propagation_0.mlp_convs.0.weight
1:
  epoch_transitions_only: true
  lr: 1.0e-03
  max_transition_epoch: 20
  params:
  - transformer_encoder.blocks.11.attn.proj.bias
  - transformer_encoder.blocks.11.attn.proj.weight
  - transformer_encoder.blocks.11.attn.qkv.weight
  - transformer_encoder.blocks.11.mlp.fc2.bias
  - transformer_encoder.blocks.11.mlp.fc2.weight
  - transformer_encoder.blocks.11.mlp.fc1.bias
  - transformer_encoder.blocks.11.mlp.fc1.weight
  - transformer_encoder.blocks.11.norm2.bias
  - transformer_encoder.blocks.11.norm2.weight
  - transformer_encoder.blocks.11.norm1.bias
  - transformer_encoder.blocks.11.norm1.weight
2:
  epoch_transitions_only: true
  lr: 1.0e-03
  max_transition_epoch: 35
  params:
  - transformer_encoder.blocks.10.attn.proj.bias
  - transformer_encoder.blocks.10.attn.proj.weight
  - transformer_encoder.blocks.10.attn.qkv.weight
  - transformer_encoder.blocks.10.mlp.fc2.bias
  - transformer_encoder.blocks.10.mlp.fc2.weight
  - transformer_encoder.blocks.10.mlp.fc1.bias
  - transformer_encoder.blocks.10.mlp.fc1.weight
  - transformer_encoder.blocks.10.norm2.bias
  - transformer_encoder.blocks.10.norm2.weight
  - transformer_encoder.blocks.10.norm1.bias
  - transformer_encoder.blocks.10.norm1.weight
3:
  epoch_transitions_only: true
  lr: 1.0e-03
  max_transition_epoch: 50
  params:
  - transformer_encoder.blocks.9.attn.proj.bias
  - transformer_encoder.blocks.9.attn.proj.weight
  - transformer_encoder.blocks.9.attn.qkv.weight
  - transformer_encoder.blocks.9.mlp.fc2.bias
  - transformer_encoder.blocks.9.mlp.fc2.weight
  - transformer_encoder.blocks.9.mlp.fc1.bias
  - transformer_encoder.blocks.9.mlp.fc1.weight
  - transformer_encoder.blocks.9.norm2.bias
  - transformer_encoder.blocks.9.norm2.weight
  - transformer_encoder.blocks.9.norm1.bias
  - transformer_encoder.blocks.9.norm1.weight
4:
  epoch_transitions_only: true
  lr: 1.0e-03
  max_transition_epoch: 65
  params:
  - transformer_encoder.blocks.8.attn.proj.bias
  - transformer_encoder.blocks.8.attn.proj.weight
  - transformer_encoder.blocks.8.attn.qkv.weight
  - transformer_encoder.blocks.8.mlp.fc2.bias
  - transformer_encoder.blocks.8.mlp.fc2.weight
  - transformer_encoder.blocks.8.mlp.fc1.bias
  - transformer_encoder.blocks.8.mlp.fc1.weight
  - transformer_encoder.blocks.8.norm2.bias
  - transformer_encoder.blocks.8.norm2.weight
  - transformer_encoder.blocks.8.norm1.bias
  - transformer_encoder.blocks.8.norm1.weight
5:
  epoch_transitions_only: true
  lr: 1.0e-03
  max_transition_epoch: 80
  params:
  - transformer_encoder.blocks.7.attn.proj.bias
  - transformer_encoder.blocks.7.attn.proj.weight
  - transformer_encoder.blocks.7.attn.qkv.weight
  - transformer_encoder.blocks.7.mlp.fc2.bias
  - transformer_encoder.blocks.7.mlp.fc2.weight
  - transformer_encoder.blocks.7.mlp.fc1.bias
  - transformer_encoder.blocks.7.mlp.fc1.weight
  - transformer_encoder.blocks.7.norm2.bias
  - transformer_encoder.blocks.7.norm2.weight
  - transformer_encoder.blocks.7.norm1.bias
  - transformer_encoder.blocks.7.norm1.weight
6:
  epoch_transitions_only: true
  lr: 1.0e-03
  max_transition_epoch: 95
  params:
  - transformer_encoder.blocks.6.attn.proj.bias
  - transformer_encoder.blocks.6.attn.proj.weight
  - transformer_encoder.blocks.6.attn.qkv.weight
  - transformer_encoder.blocks.6.mlp.fc2.bias
  - transformer_encoder.blocks.6.mlp.fc2.weight
  - transformer_encoder.blocks.6.mlp.fc1.bias
  - transformer_encoder.blocks.6.mlp.fc1.weight
  - transformer_encoder.blocks.6.norm2.bias
  - transformer_encoder.blocks.6.norm2.weight
  - transformer_encoder.blocks.6.norm1.bias
  - transformer_encoder.blocks.6.norm1.weight
7:
  epoch_transitions_only: true
  lr: 1.0e-03
  max_transition_epoch: 110
  params:
  - transformer_encoder.blocks.5.attn.proj.bias
  - transformer_encoder.blocks.5.attn.proj.weight
  - transformer_encoder.blocks.5.attn.qkv.weight
  - transformer_encoder.blocks.5.mlp.fc2.bias
  - transformer_encoder.blocks.5.mlp.fc2.weight
  - transformer_encoder.blocks.5.mlp.fc1.bias
  - transformer_encoder.blocks.5.mlp.fc1.weight
  - transformer_encoder.blocks.5.norm2.bias
  - transformer_encoder.blocks.5.norm2.weight
  - transformer_encoder.blocks.5.norm1.bias
  - transformer_encoder.blocks.5.norm1.weight
8:
  epoch_transitions_only: true
  lr: 1.0e-03
  max_transition_epoch: 125
  params:
  - transformer_encoder.blocks.4.attn.proj.bias
  - transformer_encoder.blocks.4.attn.proj.weight
  - transformer_encoder.blocks.4.attn.qkv.weight
  - transformer_encoder.blocks.4.mlp.fc2.bias
  - transformer_encoder.blocks.4.mlp.fc2.weight
  - transformer_encoder.blocks.4.mlp.fc1.bias
  - transformer_encoder.blocks.4.mlp.fc1.weight
  - transformer_encoder.blocks.4.norm2.bias
  - transformer_encoder.blocks.4.norm2.weight
  - transformer_encoder.blocks.4.norm1.bias
  - transformer_encoder.blocks.4.norm1.weight
9:
  epoch_transitions_only: true
  lr: 1.0e-03
  max_transition_epoch: 140
  params:
  - transformer_encoder.blocks.3.attn.proj.bias
  - transformer_encoder.blocks.3.attn.proj.weight
  - transformer_encoder.blocks.3.attn.qkv.weight
  - transformer_encoder.blocks.3.mlp.fc2.bias
  - transformer_encoder.blocks.3.mlp.fc2.weight
  - transformer_encoder.blocks.3.mlp.fc1.bias
  - transformer_encoder.blocks.3.mlp.fc1.weight
  - transformer_encoder.blocks.3.norm2.bias
  - transformer_encoder.blocks.3.norm2.weight
  - transformer_encoder.blocks.3.norm1.bias
  - transformer_encoder.blocks.3.norm1.weight
10:
  epoch_transitions_only: true
  lr: 1.0e-03
  max_transition_epoch: 160
  params:
  - transformer_encoder.blocks.2.attn.proj.bias
  - transformer_encoder.blocks.2.attn.proj.weight
  - transformer_encoder.blocks.2.attn.qkv.weight
  - transformer_encoder.blocks.2.mlp.fc2.bias
  - transformer_encoder.blocks.2.mlp.fc2.weight
  - transformer_encoder.blocks.2.mlp.fc1.bias
  - transformer_encoder.blocks.2.mlp.fc1.weight
  - transformer_encoder.blocks.2.norm2.bias
  - transformer_encoder.blocks.2.norm2.weight
  - transformer_encoder.blocks.2.norm1.bias
  - transformer_encoder.blocks.2.norm1.weight
11:
  epoch_transitions_only: true
  lr: 1.0e-03
  max_transition_epoch: 180
  params:
  - transformer_encoder.blocks.1.attn.proj.bias
  - transformer_encoder.blocks.1.attn.proj.weight
  - transformer_encoder.blocks.1.attn.qkv.weight
  - transformer_encoder.blocks.1.mlp.fc2.bias
  - transformer_encoder.blocks.1.mlp.fc2.weight
  - transformer_encoder.blocks.1.mlp.fc1.bias
  - transformer_encoder.blocks.1.mlp.fc1.weight
  - transformer_encoder.blocks.1.norm2.bias
  - transformer_encoder.blocks.1.norm2.weight
  - transformer_encoder.blocks.1.norm1.bias
  - transformer_encoder.blocks.1.norm1.weight
12:
  epoch_transitions_only: true
  lr: 1.0e-03
  max_transition_epoch: 200
  params:
  - transformer_encoder.blocks.0.attn.proj.bias
  - transformer_encoder.blocks.0.attn.proj.weight
  - transformer_encoder.blocks.0.attn.qkv.weight
  - transformer_encoder.blocks.0.mlp.fc2.bias
  - transformer_encoder.blocks.0.mlp.fc2.weight
  - transformer_encoder.blocks.0.mlp.fc1.bias
  - transformer_encoder.blocks.0.mlp.fc1.weight
  - transformer_encoder.blocks.0.norm2.bias
  - transformer_encoder.blocks.0.norm2.weight
  - transformer_encoder.blocks.0.norm1.bias
  - transformer_encoder.blocks.0.norm1.weight
13:
  epoch_transitions_only: true
  lr: 1.0e-03
  max_transition_epoch: 220
  params:
  - patch_encoder.conv2.3.bias
  - patch_encoder.conv2.3.weight
  - patch_encoder.conv2.1.bias
  - patch_encoder.conv2.1.weight
  - patch_encoder.conv2.0.bias
  - patch_encoder.conv2.0.weight
  - patch_encoder.conv1.3.bias
  - patch_encoder.conv1.3.weight
  - patch_encoder.conv1.1.bias
  - patch_encoder.conv1.1.weight
  - patch_encoder.conv1.0.bias
  - patch_encoder.conv1.0.weight
14:
  epoch_transitions_only: true
  lr: 1.0e-03
  max_transition_epoch: 300
  params:
  - pos_encoder.encoder.2.bias
  - pos_encoder.encoder.2.weight
  - pos_encoder.encoder.0.bias
  - pos_encoder.encoder.0.weight
