wandb:
  project: PRETRAIN_TLSPT_2025
  entity: mja2106
  mode: online
experiment_name: test_pretrain

hydra:
  run:
    dir: /home/mja78/rds/hpc-work/hydra/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: false

devices: 4

max_epochs: 300
strategy: ddp
profiler: null
matmul_precision: 'high'
num_points: 8192
seed: 0

split_files:
  - "${hydra:runtime.cwd}/data/supertree/plot_octrees_1cm/hjfo-fin/hjfo-fin-splits.csv"
  - "${hydra:runtime.cwd}/data/supertree/plot_octrees_1cm/hjfo-pol/hjfo-pol-splits.csv"
  - "${hydra:runtime.cwd}/data/supertree/plot_octrees_1cm/hjfo-spa/hjfo-spa-splits.csv"
  - "${hydra:runtime.cwd}/data/supertree/plot_octrees_1cm/widi-ank/widi-ank-splits.csv"
  - "${hydra:runtime.cwd}/data/supertree/plot_octrees_1cm/widi-aus/widi-aus-splits.csv"
  - "${hydra:runtime.cwd}/data/supertree/plot_octrees_1cm/widi-bra/widi-bra-splits.csv"
  - "${hydra:runtime.cwd}/data/supertree/plot_octrees_1cm/widi-cali/widi-cali-splits.csv"
  - "${hydra:runtime.cwd}/data/supertree/plot_octrees_1cm/widi-fgu/widi-fgu-splits.csv"
  - "${hydra:runtime.cwd}/data/supertree/plot_octrees_1cm/widi-gab/widi-gab-splits.csv"
  - "${hydra:runtime.cwd}/data/supertree/plot_octrees_1cm/widi-mly/widi-mly-splits.csv"
  - "${hydra:runtime.cwd}/data/supertree/plot_octrees_1cm/widi-per/widi-per-splits.csv"
min_points: 512
scales: 2
feature_names: null

datamodule:
  _target_: tlspt.datamodules.single_datamodule.SingleDataModule
  num_workers: 28
  prefetch_factor: 8
  persistent_workers: True
  pin_memory: True
  batch_size: 64

  limit_train_pct: 1.0
  limit_val_pct: 1.0
  limit_test_pct: 1.0

  train_dataset:
    target_class: tlspt.datamodules.components.merged_dataset.MergedOctreeDataset
    kwargs:
      split_files: ${split_files}
      split: train
      scales: ${scales} #One for each dataset
      min_points: ${min_points} #One for each dataset
      feature_names: ${feature_names}
      features_to_normalize: null
      normalize: True
      transform:
        _target_: tlspt.transforms.UniformTLSSampler
        num_points: ${num_points}

  val_dataset:
    target_class: tlspt.datamodules.components.merged_dataset.MergedOctreeDataset
    kwargs:
      split_files: ${split_files}
      split: val
      scales: ${scales} #One for each dataset
      min_points: ${min_points} #One for each dataset
      feature_names: ${feature_names}
      features_to_normalize: null
      normalize: True
      transform:
        _target_: tlspt.transforms.UniformTLSSampler
        num_points: ${num_points}

  test_dataset:
    target_class: tlspt.datamodules.components.merged_dataset.MergedOctreeDataset
    kwargs:
      split_files: ${split_files}
      split: test
      scales: ${scales} #One for each dataset
      min_points: ${min_points} #One for each dataset
      feature_names: ${feature_names}
      features_to_normalize: null
      normalize: True
      transform:
        _target_: tlspt.transforms.UniformTLSSampler
        num_points: ${num_points}

model:
  _target_: tlspt.models.pointmae.pointmae_bool.PointMAE
  neighbor_alg: ball_query
  ball_radius: 0.2
  scale: 2.0
  total_epochs: ${max_epochs}
  warmup_epochs: 10
  num_centers: 196
  num_neighbors: 32
  embedding_dim: 768 #Width
  mask_ratio: 0.7
  mask_type: random
  transencoder_config:
    embed_dim: ${model.embedding_dim}
    depth: 12 #Depth
    num_heads: 12 #Heads
    mlp_ratio: 4.0 #MLP
  transdecoder_config:
    embed_dim: ${model.embedding_dim}
    depth: 4 #Depth
    num_heads: 6 #Heads
    mlp_ratio: 4.0 #MLP
