wandb:
  project: tlspt_dev
  entity: mja2106
  mode: online
experiment_name: scaletest_cluster

max_epochs: 20
strategy: ddp
profiler: null
checkpoint_dir: /home/mja78/rds/hpc-work/tlspt-checkpoints
matmul_precision: 'high'

dataloader:
  _target_: tlspt.datamodules.single_datamodule.SingleDataModule
  num_workers: 24
  prefetch_factor: 1
  persistent_workers: True
  pin_memory: True
  batch_size: 128

  train_dataset:
    target_class: tlspt.datamodules.components.merged_dataset.MergedOctreeDataset
    kwargs:
      split_files:
        - '${hydra:runtime.cwd}/data/plot_octrees/allen-spain/octrees/allen-spain-plot_splits-tr0.7-val0.15-te0.15_seed0.csv'
        - '${hydra:runtime.cwd}/data/plot_octrees/allen-finland/octrees/allen-finland-plot_splits-tr0.7-val0.15-te0.15_seed0.csv'
        - '${hydra:runtime.cwd}/data/plot_octrees/allen-poland/octrees/allen-poland-plot_splits-tr0.7-val0.15-te0.15_seed0.csv'
      split: train
      scales: [1.5, 1.5, 1.5]
      min_points: [512, 512, 512]
      feature_names: null
      normalize: True
      transform:
        _target_: tlspt.transforms.UniformTLSSampler
        num_points: 16384

  val_dataset:
    target_class: tlspt.datamodules.components.merged_dataset.MergedOctreeDataset
    kwargs:
      split_files:
        - '${hydra:runtime.cwd}/data/plot_octrees/allen-spain/octrees/allen-spain-plot_splits-tr0.7-val0.15-te0.15_seed0.csv'
        - '${hydra:runtime.cwd}/data/plot_octrees/allen-finland/octrees/allen-finland-plot_splits-tr0.7-val0.15-te0.15_seed0.csv'
        - '${hydra:runtime.cwd}/data/plot_octrees/allen-poland/octrees/allen-poland-plot_splits-tr0.7-val0.15-te0.15_seed0.csv'
      split: val
      scales: [1.5, 1.5, 1.5]
      min_points: [512, 512, 512]
      feature_names: null
      normalize: True
      transform:
        _target_: tlspt.transforms.UniformTLSSampler
        num_points: 16384

  test_dataset:
    target_class: tlspt.datamodules.components.merged_dataset.MergedOctreeDataset
    kwargs:
      split_files:
        - '${hydra:runtime.cwd}/data/plot_octrees/allen-spain/octrees/allen-spain-plot_splits-tr0.7-val0.15-te0.15_seed0.csv'
        - '${hydra:runtime.cwd}/data/plot_octrees/allen-finland/octrees/allen-finland-plot_splits-tr0.7-val0.15-te0.15_seed0.csv'
        - '${hydra:runtime.cwd}/data/plot_octrees/allen-poland/octrees/allen-poland-plot_splits-tr0.7-val0.15-te0.15_seed0.csv'
      split: test
      scales: [1.5, 1.5, 1.5]
      min_points: [512, 512, 512]
      feature_names: null
      normalize: True
      transform:
        _target_: tlspt.transforms.UniformTLSSampler
        num_points: 16384

Config:

model:
  _target_: tlspt.models.pointmae.pointmae_bool.PointMAE
  neighbor_alg: ball_query
  ball_radius: 0.1
  total_epochs: ${max_epochs}
  warmup_epochs: 10
  num_centers: 196
  num_neighbors: 64
  embedding_dim: 384 #Width
  mask_ratio: 0.75
  mask_type: random
  transencoder_config:
    embed_dim: ${model.embedding_dim}
    depth: 12 #Depth
    num_heads: 6 #Heads
    mlp_ratio: 4.0 #MLP
  transdecoder_config:
    embed_dim: ${model.embedding_dim}
    depth: 4 #Depth
    num_heads: 6 #Heads
    mlp_ratio: 4.0 #MLP
