wandb:
  project: tlspt_dev
  entity: mja2106
  mode: online
experiment_name: scaletest_cluster

max_epochs: 20
strategy: ddp
profiler: null
#checkpoint_dir: /home/mja78/rds/hpc-work/tlspt-checkpoints
matmul_precision: 'high'
num_points: 8192

limit_train_batches: 0.1
limit_val_batches: 0.1
limit_test_batches: 0.1

dataloader:
  _target_: tlspt.datamodules.single_datamodule.SingleDataModule
  num_workers: 24
  prefetch_factor: 1
  persistent_workers: True
  pin_memory: True
  batch_size: 32

  train_dataset:
    target_class: tlspt.datamodules.components.merged_dataset.MergedOctreeDataset
    kwargs:
      split_files:
        - '${hydra:runtime.cwd}/data/plot_octrees/allen-spain/octrees/____TEST.csv'
      split: train
      scales: [2]
      min_points: [512]
      feature_names: ['scalar_label']
      features_to_normalize: null
      normalize: True
      transform:
        _target_: tlspt.transforms.UniformTLSSampler
        num_points: ${num_points}

  val_dataset:
    target_class: tlspt.datamodules.components.merged_dataset.MergedOctreeDataset
    kwargs:
      split_files:
        - '${hydra:runtime.cwd}/data/plot_octrees/allen-spain/octrees/____TEST.csv'
      split: val
      scales: [2]
      min_points: [512]
      feature_names: ['scalar_label']
      features_to_normalize: null
      normalize: True
      transform:
        _target_: tlspt.transforms.UniformTLSSampler
        num_points: ${num_points}

  test_dataset:
    target_class: tlspt.datamodules.components.merged_dataset.MergedOctreeDataset
    kwargs:
      split_files:
        - '${hydra:runtime.cwd}/data/plot_octrees/allen-spain/octrees/____TEST.csv'
      split: test
      scales: [2]
      min_points: [512]
      feature_names: ['scalar_label']
      features_to_normalize: null
      normalize: True
      transform:
        _target_: tlspt.transforms.UniformTLSSampler
        num_points: ${num_points}

#VITB
# model:
#   _target_: tlspt.models.pointmae.pointmae_seg.PointMAESegmentation
#   neighbor_alg: ball_query
#   ball_radius: 0.1
#   scale: 2.0
#   total_epochs: ${max_epochs}
#   warmup_epochs: 10
#   num_centers: 196
#   num_neighbors: 64
#   embedding_dim: 768 #Width
#   feature_blocks: Sumfin bigger
#   transencoder_config:
#     embed_dim: ${model.embedding_dim}
#     depth: 12 #Depth
#     num_heads: 12 #Heads
#     mlp_ratio: 4.0 #MLP

#VITS
model:
  _target_: tlspt.models.pointmae.pointmae_seg.PointMAESegmentation
  neighbor_alg: ball_query
  ball_radius: 0.1
  scale: 2.0
  total_epochs: ${max_epochs}
  warmup_epochs: 10
  num_centers: 196
  num_neighbors: 64
  embedding_dim: 384 #Width
  transencoder_config:
    embed_dim: ${model.embedding_dim}
    depth: 12 #Depth
    num_heads: 6 #Heads
    mlp_ratio: 4.0 #MLP
