wandb:
  project: tlspt_dev
  entity: mja2106
  mode: offline

dataloader:
  _target_: tlspt.datamodules.single_datamodule.SingleDataModule

  train_dataset:
    target_class:  tlspt.datamodules.components.numpy_dataset.NumpyDataset
    kwargs:
      split: train
      split_file: /home/matt/work/tlsPT/data/dummy_data/splits.csv
      num_channels: 3
      has_labels: False
      normalize: True
      transform: null

  val_dataset:
    target_class:  tlspt.datamodules.components.numpy_dataset.NumpyDataset
    kwargs:
      split: val
      split_file: /home/matt/work/tlsPT/data/dummy_data/splits.csv
      num_channels: 3
      has_labels: False
      normalize: True
      transform: null

  test_dataset:
    target_class:  tlspt.datamodules.components.numpy_dataset.NumpyDataset
    kwargs:
      split: test
      split_file: /home/matt/work/tlsPT/data/dummy_data/splits.csv
      num_channels: 3
      has_labels: False
      normalize: True
      transform: null

max_epochs: 5

experiment_name: test
